basic:
    name: 'Clarkston Consulting'
    environments:
        production: 'https://clarkstonconsulting.com/'
        staging: 'https://test-clarkstonconsulting.pantheonsite.io/'
        development: 'https://dev-clarkstonconsulting.pantheonsite.io/'
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - industries
        - insights/life-sciences-insights-from-2024
        - insights/consumer-products-insights-from-2024
        - insights/retail-insights-from-2024
        - industries/life-sciences
        - industries/life-sciences/medical-device-consulting
        - cell-gene-therapy
        - industries/life-sciences/contract-manufacturing-consulting
        - industries/life-sciences/generics-consulting
        - industries/consumer-products
        - industries/consumer-products/fast-moving-consumer-goods-consulting
        - industries/consumer-products/wholesale-distribution-consulting-consumer-products
        - industries/retail-consulting
        - industries/retail-consulting/specialty-retail-consulting
        - industries/retail-consulting/mass-merchant-drug-club
        - services
        - services/sap-consulting-technology/sap-s4hana-upgrade
        - services/private-equity-consulting-services
        - services/people-and-change-consulting/business-process-consulting
        - services/quality-compliance/veeva-consulting
        - services/supply-chain/logility-consulting
        - services/people-and-change-consulting/retail-project-management-consulting
        - services/data-analytics
        - services/data-analytics/ai-consulting
        - services/data-analytics/data-consulting/data-engineering
        - services/data-analytics/data-consulting/data-management
        - services/data-analytics/data-consulting/data-strategy
        - services/it-consulting
        - services/it-consulting/it-strategy
        - services/it-consulting/vendor-selection-advisory
        - services/digital-consulting-services
        - services/strategy-innovation
        - services/strategy-innovation/mergers-consulting
        - services/people-and-change-consulting
        - services/people-and-change-consulting/project-management-consulting
        - services/people-and-change-consulting/diversity-equity-inclusion-dei-consulting
        - services/quality-compliance
        - services/quality-compliance/lims-consulting
        - services/quality-compliance/quality-operations-processes-systems
        - services/sales-marketing
        - services/sales-marketing/category-management-consulting
        - services/sales-marketing/trade-promotion
        - services/sales-marketing/life-sciences-sales-marketing-consulting
        - services/sap-consulting-technology
        - services/sap-consulting-technology/sap-solutions
        - services/sap-consulting-technology/sap-signavio
        - services/sap-consulting-technology/sap-ibp
        - services/supply-chain
        - services/supply-chain/supply-chain-planning-execution-consumer-products
        - services/supply-chain/strategic-sourcing-consulting
        - insights
        - insights/erp-vendor-selection-case-study
        - insights/building-a-direct-to-consumer-strategy-a-case-study
        - insights/digital-analytics-audit-and-tagging-case-study
        - insights/developing-a-forecasting-modeling-tool
        - insights/decision-making-during-times-of-uncertainty
        - insights/2025-consumer-products-supply-chain-trends
        - insights/post-merger-clinical-operations-support
        - insights/data-strategy-with-sap-business-data-cloud
        - clients-case-studies
        - insights/clinical-lims-enhancement
        - insights/designing-a-retail-organization
        - clarkston-webinars
        - insights/category-management-playbook
        - insights/2025-medical-device-industry-trends
        - about-us
        - amplifiers
        - clarkston-scholars-program
        - corporate-training
        - about-us/clarkston-global
        - about-us/leadership
        - about-us/clarkston-culture-and-community
        - about-us/diversity
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
